version: "3"

volumes:
    etcd-data:

services:
    etcd1:
        image: bitnami/etcd
        volumes:
            - etcd-data:/bitnami/etcd/data
        environment: 
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_NAME=etcd1
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
        ports:
            - 2379:2379

    redis:
        image: redis:6-alpine
        ports:
            - 6379:6379

