version: "3"

services:
    etcd1:
        image: bitnami/etcd
        volumes:
            - etcd-data1:/bitnami/etcd/data
        environment: 
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_NAME=etcd1
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
        ports:
            - 2379:2379

    redis1:
        image: redis:6-alpine
        volumes:
            - redis-data1:/data
        ports:
            - 6379:6379

volumes:
    etcd-data1:
    redis-data1: