version: "3"

services:
    etcd:
        image: bitnami/etcd
        volumes:
            - etcd-data:/bitnami/etcd/data
        environment: 
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_NAME=etcd1
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
        ports:
            - 2379:2379

    redis:
        image: redis:6-alpine
        volumes:
            - redis-data:/data
        ports:
            - 6379:6379

    mongo:
        image: mongo:4.4-bionic
        environment:
            - MONGO_INITDB_ROOT_USERNAME: admin
            - MONGO_INITDB_ROOT_PASSWORD: cuKpVrfZzUvg
        volumes:
            - mongo-data:/data/db
        ports:
            - 27017:27017

volumes:
    etcd-data:
    redis-data:
    mongo-data: