// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gateway_api.proto

package protocol

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 心跳
type ClientPingReq struct {
	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (m *ClientPingReq) Reset()         { *m = ClientPingReq{} }
func (m *ClientPingReq) String() string { return proto.CompactTextString(m) }
func (*ClientPingReq) ProtoMessage()    {}
func (*ClientPingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19061a37068d4c6, []int{0}
}
func (m *ClientPingReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientPingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientPingReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientPingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPingReq.Merge(m, src)
}
func (m *ClientPingReq) XXX_Size() int {
	return m.Size()
}
func (m *ClientPingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPingReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPingReq proto.InternalMessageInfo

func (m *ClientPingReq) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type ClientPongAck struct {
	Time int64 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (m *ClientPongAck) Reset()         { *m = ClientPongAck{} }
func (m *ClientPongAck) String() string { return proto.CompactTextString(m) }
func (*ClientPongAck) ProtoMessage()    {}
func (*ClientPongAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19061a37068d4c6, []int{1}
}
func (m *ClientPongAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientPongAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientPongAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientPongAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPongAck.Merge(m, src)
}
func (m *ClientPongAck) XXX_Size() int {
	return m.Size()
}
func (m *ClientPongAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPongAck.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPongAck proto.InternalMessageInfo

func (m *ClientPongAck) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// 通知客户端掉线
type ClientDisconnectNtf struct {
	Reason uint32 `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *ClientDisconnectNtf) Reset()         { *m = ClientDisconnectNtf{} }
func (m *ClientDisconnectNtf) String() string { return proto.CompactTextString(m) }
func (*ClientDisconnectNtf) ProtoMessage()    {}
func (*ClientDisconnectNtf) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19061a37068d4c6, []int{2}
}
func (m *ClientDisconnectNtf) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientDisconnectNtf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientDisconnectNtf.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientDisconnectNtf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientDisconnectNtf.Merge(m, src)
}
func (m *ClientDisconnectNtf) XXX_Size() int {
	return m.Size()
}
func (m *ClientDisconnectNtf) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientDisconnectNtf.DiscardUnknown(m)
}

var xxx_messageInfo_ClientDisconnectNtf proto.InternalMessageInfo

func (m *ClientDisconnectNtf) GetReason() uint32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

//握手
type ClientHandShakeReq struct {
	Method uint32 `protobuf:"varint,1,opt,name=method,proto3" json:"method,omitempty"`
	Key    []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Salt   []byte `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	Iv     uint64 `protobuf:"varint,4,opt,name=iv,proto3" json:"iv,omitempty"`
}

func (m *ClientHandShakeReq) Reset()         { *m = ClientHandShakeReq{} }
func (m *ClientHandShakeReq) String() string { return proto.CompactTextString(m) }
func (*ClientHandShakeReq) ProtoMessage()    {}
func (*ClientHandShakeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19061a37068d4c6, []int{3}
}
func (m *ClientHandShakeReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientHandShakeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientHandShakeReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientHandShakeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientHandShakeReq.Merge(m, src)
}
func (m *ClientHandShakeReq) XXX_Size() int {
	return m.Size()
}
func (m *ClientHandShakeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientHandShakeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClientHandShakeReq proto.InternalMessageInfo

func (m *ClientHandShakeReq) GetMethod() uint32 {
	if m != nil {
		return m.Method
	}
	return 0
}

func (m *ClientHandShakeReq) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ClientHandShakeReq) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *ClientHandShakeReq) GetIv() uint64 {
	if m != nil {
		return m.Iv
	}
	return 0
}

type ClientHandShakeAck struct {
	Method uint32 `protobuf:"varint,1,opt,name=method,proto3" json:"method,omitempty"`
	Key    []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Salt   []byte `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	Iv     uint64 `protobuf:"varint,4,opt,name=iv,proto3" json:"iv,omitempty"`
	Seq    uint32 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (m *ClientHandShakeAck) Reset()         { *m = ClientHandShakeAck{} }
func (m *ClientHandShakeAck) String() string { return proto.CompactTextString(m) }
func (*ClientHandShakeAck) ProtoMessage()    {}
func (*ClientHandShakeAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19061a37068d4c6, []int{4}
}
func (m *ClientHandShakeAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientHandShakeAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientHandShakeAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientHandShakeAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientHandShakeAck.Merge(m, src)
}
func (m *ClientHandShakeAck) XXX_Size() int {
	return m.Size()
}
func (m *ClientHandShakeAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientHandShakeAck.DiscardUnknown(m)
}

var xxx_messageInfo_ClientHandShakeAck proto.InternalMessageInfo

func (m *ClientHandShakeAck) GetMethod() uint32 {
	if m != nil {
		return m.Method
	}
	return 0
}

func (m *ClientHandShakeAck) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ClientHandShakeAck) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *ClientHandShakeAck) GetIv() uint64 {
	if m != nil {
		return m.Iv
	}
	return 0
}

func (m *ClientHandShakeAck) GetSeq() uint32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func init() {
	proto.RegisterType((*ClientPingReq)(nil), "protocol.ClientPingReq")
	proto.RegisterType((*ClientPongAck)(nil), "protocol.ClientPongAck")
	proto.RegisterType((*ClientDisconnectNtf)(nil), "protocol.ClientDisconnectNtf")
	proto.RegisterType((*ClientHandShakeReq)(nil), "protocol.ClientHandShakeReq")
	proto.RegisterType((*ClientHandShakeAck)(nil), "protocol.ClientHandShakeAck")
}

func init() { proto.RegisterFile("gateway_api.proto", fileDescriptor_d19061a37068d4c6) }

var fileDescriptor_d19061a37068d4c6 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x4f, 0x2c, 0x49,
	0x2d, 0x4f, 0xac, 0x8c, 0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00,
	0x53, 0xc9, 0xf9, 0x39, 0x52, 0x22, 0xe9, 0xf9, 0xe9, 0xf9, 0x60, 0x9e, 0x3e, 0x88, 0x05, 0x91,
	0x57, 0x52, 0xe6, 0xe2, 0x75, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x09, 0xc8, 0xcc, 0x4b, 0x0f, 0x4a,
	0x2d, 0x14, 0x12, 0xe2, 0x62, 0x29, 0xc9, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e,
	0x02, 0xb3, 0x91, 0x14, 0xe5, 0xe7, 0xa5, 0x3b, 0x26, 0x67, 0xc3, 0x15, 0x31, 0x21, 0x29, 0xd2,
	0xe5, 0x12, 0x86, 0x28, 0x72, 0xc9, 0x2c, 0x4e, 0xce, 0xcf, 0xcb, 0x4b, 0x4d, 0x2e, 0xf1, 0x2b,
	0x49, 0x13, 0x12, 0xe3, 0x62, 0x2b, 0x4a, 0x4d, 0x2c, 0xce, 0xcf, 0x03, 0x2b, 0xe6, 0x0d, 0x82,
	0xf2, 0x94, 0x92, 0xb8, 0x84, 0x20, 0xca, 0x3d, 0x12, 0xf3, 0x52, 0x82, 0x33, 0x12, 0xb3, 0x53,
	0x41, 0xb6, 0x8b, 0x71, 0xb1, 0xe5, 0xa6, 0x96, 0x64, 0xe4, 0xa7, 0x80, 0xed, 0xe7, 0x0d, 0x82,
	0xf2, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0xc1, 0x46, 0xf0, 0x04, 0x81, 0x98, 0x20, 0x27,
	0x14, 0x27, 0xe6, 0x94, 0x48, 0x30, 0x83, 0x85, 0xc0, 0x6c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x32,
	0x09, 0x16, 0x05, 0x46, 0x0d, 0x96, 0x20, 0xa6, 0xcc, 0x32, 0xa5, 0x12, 0x0c, 0x3b, 0x40, 0x8e,
	0xa7, 0xaa, 0x1d, 0x20, 0x5d, 0xc5, 0xa9, 0x85, 0x12, 0xac, 0x60, 0xa3, 0x40, 0x4c, 0x27, 0x99,
	0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39,
	0x86, 0x19, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0x89, 0x0d,
	0x1c, 0xee, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x12, 0x94, 0x7d, 0x26, 0xac, 0x01, 0x00,
	0x00,
}

func (m *ClientPingReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientPingReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientPingReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Time != 0 {
		i = encodeVarintGatewayApi(dAtA, i, uint64(m.Time))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ClientPongAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientPongAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientPongAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Time != 0 {
		i = encodeVarintGatewayApi(dAtA, i, uint64(m.Time))
		i--
		dAtA[i] = 0x10
	}
	return len(dAtA) - i, nil
}

func (m *ClientDisconnectNtf) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientDisconnectNtf) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientDisconnectNtf) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reason != 0 {
		i = encodeVarintGatewayApi(dAtA, i, uint64(m.Reason))
		i--
		dAtA[i] = 0x10
	}
	return len(dAtA) - i, nil
}

func (m *ClientHandShakeReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientHandShakeReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientHandShakeReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Iv != 0 {
		i = encodeVarintGatewayApi(dAtA, i, uint64(m.Iv))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Salt) > 0 {
		i -= len(m.Salt)
		copy(dAtA[i:], m.Salt)
		i = encodeVarintGatewayApi(dAtA, i, uint64(len(m.Salt)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintGatewayApi(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0x12
	}
	if m.Method != 0 {
		i = encodeVarintGatewayApi(dAtA, i, uint64(m.Method))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ClientHandShakeAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientHandShakeAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientHandShakeAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Seq != 0 {
		i = encodeVarintGatewayApi(dAtA, i, uint64(m.Seq))
		i--
		dAtA[i] = 0x28
	}
	if m.Iv != 0 {
		i = encodeVarintGatewayApi(dAtA, i, uint64(m.Iv))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Salt) > 0 {
		i -= len(m.Salt)
		copy(dAtA[i:], m.Salt)
		i = encodeVarintGatewayApi(dAtA, i, uint64(len(m.Salt)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintGatewayApi(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0x12
	}
	if m.Method != 0 {
		i = encodeVarintGatewayApi(dAtA, i, uint64(m.Method))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGatewayApi(dAtA []byte, offset int, v uint64) int {
	offset -= sovGatewayApi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ClientPingReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Time != 0 {
		n += 1 + sovGatewayApi(uint64(m.Time))
	}
	return n
}

func (m *ClientPongAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Time != 0 {
		n += 1 + sovGatewayApi(uint64(m.Time))
	}
	return n
}

func (m *ClientDisconnectNtf) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Reason != 0 {
		n += 1 + sovGatewayApi(uint64(m.Reason))
	}
	return n
}

func (m *ClientHandShakeReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Method != 0 {
		n += 1 + sovGatewayApi(uint64(m.Method))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovGatewayApi(uint64(l))
	}
	l = len(m.Salt)
	if l > 0 {
		n += 1 + l + sovGatewayApi(uint64(l))
	}
	if m.Iv != 0 {
		n += 1 + sovGatewayApi(uint64(m.Iv))
	}
	return n
}

func (m *ClientHandShakeAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Method != 0 {
		n += 1 + sovGatewayApi(uint64(m.Method))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovGatewayApi(uint64(l))
	}
	l = len(m.Salt)
	if l > 0 {
		n += 1 + l + sovGatewayApi(uint64(l))
	}
	if m.Iv != 0 {
		n += 1 + sovGatewayApi(uint64(m.Iv))
	}
	if m.Seq != 0 {
		n += 1 + sovGatewayApi(uint64(m.Seq))
	}
	return n
}

func sovGatewayApi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGatewayApi(x uint64) (n int) {
	return sovGatewayApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClientPingReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGatewayApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientPingReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientPingReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGatewayApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientPongAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGatewayApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientPongAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientPongAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGatewayApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientDisconnectNtf) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGatewayApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientDisconnectNtf: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientDisconnectNtf: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			m.Reason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reason |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGatewayApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientHandShakeReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGatewayApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientHandShakeReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientHandShakeReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			m.Method = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Method |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGatewayApi
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Salt", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGatewayApi
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Salt = append(m.Salt[:0], dAtA[iNdEx:postIndex]...)
			if m.Salt == nil {
				m.Salt = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Iv", wireType)
			}
			m.Iv = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Iv |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGatewayApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientHandShakeAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGatewayApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientHandShakeAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientHandShakeAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			m.Method = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Method |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGatewayApi
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Salt", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGatewayApi
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Salt = append(m.Salt[:0], dAtA[iNdEx:postIndex]...)
			if m.Salt == nil {
				m.Salt = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Iv", wireType)
			}
			m.Iv = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Iv |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			m.Seq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seq |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGatewayApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGatewayApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGatewayApi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGatewayApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGatewayApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGatewayApi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGatewayApi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGatewayApi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGatewayApi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGatewayApi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGatewayApi = fmt.Errorf("proto: unexpected end of group")
)
