// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal_struct.proto

package protocol

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 节点状态
type NodeState int32

const (
	StateDown NodeState = 0
	StateUp   NodeState = 1
)

var NodeState_name = map[int32]string{
	0: "StateDown",
	1: "StateUp",
}

var NodeState_value = map[string]int32{
	"StateDown": 0,
	"StateUp":   1,
}

func (x NodeState) String() string {
	return proto.EnumName(NodeState_name, int32(x))
}

func (NodeState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cfb596b5e210fda8, []int{0}
}

// 通用环境变量
type Environ struct {
	AppEnv            string           `protobuf:"bytes,1,opt,name=app_env,json=appEnv,proto3" json:"app_env,omitempty"`
	AppGameId         string           `protobuf:"bytes,2,opt,name=app_game_id,json=appGameId,proto3" json:"app_game_id,omitempty"`
	AppChannelId      string           `protobuf:"bytes,3,opt,name=app_channel_id,json=appChannelId,proto3" json:"app_channel_id,omitempty"`
	AppServerId       string           `protobuf:"bytes,4,opt,name=app_server_id,json=appServerId,proto3" json:"app_server_id,omitempty"`
	AppServerName     string           `protobuf:"bytes,5,opt,name=app_server_name,json=appServerName,proto3" json:"app_server_name,omitempty"`
	AppAccessKey      string           `protobuf:"bytes,6,opt,name=app_access_key,json=appAccessKey,proto3" json:"app_access_key,omitempty"`
	AppLogLevel       string           `protobuf:"bytes,7,opt,name=app_log_level,json=appLogLevel,proto3" json:"app_log_level,omitempty"`
	AppPprofAddr      string           `protobuf:"bytes,19,opt,name=app_pprof_addr,json=appPprofAddr,proto3" json:"app_pprof_addr,omitempty"`
	AppWorkingDir     string           `protobuf:"bytes,20,opt,name=app_working_dir,json=appWorkingDir,proto3" json:"app_working_dir,omitempty"`
	ServiceType       string           `protobuf:"bytes,10,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	ServiceIndex      int32            `protobuf:"varint,11,opt,name=service_index,json=serviceIndex,proto3" json:"service_index,omitempty"`
	ServiceDependency string           `protobuf:"bytes,12,opt,name=service_dependency,json=serviceDependency,proto3" json:"service_dependency,omitempty"`
	EtcdAddr          string           `protobuf:"bytes,13,opt,name=etcd_addr,json=etcdAddr,proto3" json:"etcd_addr,omitempty"`
	EtcdKeyspace      string           `protobuf:"bytes,14,opt,name=etcd_keyspace,json=etcdKeyspace,proto3" json:"etcd_keyspace,omitempty"`
	EtcdLeaseTtl      int32            `protobuf:"varint,15,opt,name=etcd_lease_ttl,json=etcdLeaseTtl,proto3" json:"etcd_lease_ttl,omitempty"`
	NetInterfaces     []*InterfaceAddr `protobuf:"bytes,22,rep,name=net_interfaces,json=netInterfaces,proto3" json:"net_interfaces,omitempty"`
}

func (m *Environ) Reset()         { *m = Environ{} }
func (m *Environ) String() string { return proto.CompactTextString(m) }
func (*Environ) ProtoMessage()    {}
func (*Environ) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfb596b5e210fda8, []int{0}
}
func (m *Environ) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Environ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Environ.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Environ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environ.Merge(m, src)
}
func (m *Environ) XXX_Size() int {
	return m.Size()
}
func (m *Environ) XXX_DiscardUnknown() {
	xxx_messageInfo_Environ.DiscardUnknown(m)
}

var xxx_messageInfo_Environ proto.InternalMessageInfo

func (m *Environ) GetAppEnv() string {
	if m != nil {
		return m.AppEnv
	}
	return ""
}

func (m *Environ) GetAppGameId() string {
	if m != nil {
		return m.AppGameId
	}
	return ""
}

func (m *Environ) GetAppChannelId() string {
	if m != nil {
		return m.AppChannelId
	}
	return ""
}

func (m *Environ) GetAppServerId() string {
	if m != nil {
		return m.AppServerId
	}
	return ""
}

func (m *Environ) GetAppServerName() string {
	if m != nil {
		return m.AppServerName
	}
	return ""
}

func (m *Environ) GetAppAccessKey() string {
	if m != nil {
		return m.AppAccessKey
	}
	return ""
}

func (m *Environ) GetAppLogLevel() string {
	if m != nil {
		return m.AppLogLevel
	}
	return ""
}

func (m *Environ) GetAppPprofAddr() string {
	if m != nil {
		return m.AppPprofAddr
	}
	return ""
}

func (m *Environ) GetAppWorkingDir() string {
	if m != nil {
		return m.AppWorkingDir
	}
	return ""
}

func (m *Environ) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *Environ) GetServiceIndex() int32 {
	if m != nil {
		return m.ServiceIndex
	}
	return 0
}

func (m *Environ) GetServiceDependency() string {
	if m != nil {
		return m.ServiceDependency
	}
	return ""
}

func (m *Environ) GetEtcdAddr() string {
	if m != nil {
		return m.EtcdAddr
	}
	return ""
}

func (m *Environ) GetEtcdKeyspace() string {
	if m != nil {
		return m.EtcdKeyspace
	}
	return ""
}

func (m *Environ) GetEtcdLeaseTtl() int32 {
	if m != nil {
		return m.EtcdLeaseTtl
	}
	return 0
}

func (m *Environ) GetNetInterfaces() []*InterfaceAddr {
	if m != nil {
		return m.NetInterfaces
	}
	return nil
}

// 地址接口，对外地址@bind地址:端口，如example.com@0.0.0.0:9527
type InterfaceAddr struct {
	BindAddr      string `protobuf:"bytes,1,opt,name=bind_addr,json=bindAddr,proto3" json:"bind_addr,omitempty"`
	AdvertiseAddr string `protobuf:"bytes,2,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	Port          int32  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (m *InterfaceAddr) Reset()         { *m = InterfaceAddr{} }
func (m *InterfaceAddr) String() string { return proto.CompactTextString(m) }
func (*InterfaceAddr) ProtoMessage()    {}
func (*InterfaceAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfb596b5e210fda8, []int{1}
}
func (m *InterfaceAddr) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InterfaceAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InterfaceAddr.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InterfaceAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceAddr.Merge(m, src)
}
func (m *InterfaceAddr) XXX_Size() int {
	return m.Size()
}
func (m *InterfaceAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceAddr.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceAddr proto.InternalMessageInfo

func (m *InterfaceAddr) GetBindAddr() string {
	if m != nil {
		return m.BindAddr
	}
	return ""
}

func (m *InterfaceAddr) GetAdvertiseAddr() string {
	if m != nil {
		return m.AdvertiseAddr
	}
	return ""
}

func (m *InterfaceAddr) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// 节点信息
type NodeInfo struct {
	Node      uint32 `protobuf:"varint,1,opt,name=node,proto3" json:"node,omitempty"`
	Interface string `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfb596b5e210fda8, []int{2}
}
func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return m.Size()
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetNode() uint32 {
	if m != nil {
		return m.Node
	}
	return 0
}

func (m *NodeInfo) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func init() {
	proto.RegisterEnum("protocol.NodeState", NodeState_name, NodeState_value)
	proto.RegisterType((*Environ)(nil), "protocol.Environ")
	proto.RegisterType((*InterfaceAddr)(nil), "protocol.InterfaceAddr")
	proto.RegisterType((*NodeInfo)(nil), "protocol.NodeInfo")
}

func init() { proto.RegisterFile("internal_struct.proto", fileDescriptor_cfb596b5e210fda8) }

var fileDescriptor_cfb596b5e210fda8 = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x93, 0xfd, 0x6b, 0xe3, 0x36, 0xdd, 0x30, 0x83, 0x59, 0x80, 0xa2, 0xd2, 0x0d, 0xa8,
	0x90, 0x28, 0x12, 0x5c, 0x11, 0xd2, 0xa0, 0x13, 0x8a, 0x56, 0x4d, 0xa8, 0x1b, 0xe2, 0x18, 0x79,
	0xf1, 0xdb, 0x10, 0x35, 0xb5, 0x2d, 0xc7, 0x64, 0xe4, 0x5b, 0x70, 0xe4, 0xe3, 0x70, 0xe4, 0xd8,
	0x23, 0x47, 0x68, 0x8f, 0x7c, 0x09, 0x64, 0xa7, 0x89, 0xe0, 0x94, 0x37, 0xbf, 0xe7, 0xf1, 0xfb,
	0x3e, 0xb6, 0x5e, 0x74, 0x27, 0xe5, 0x1a, 0x14, 0xa7, 0x59, 0x94, 0x6b, 0xf5, 0x39, 0xd6, 0x23,
	0xa9, 0x84, 0x16, 0xb8, 0x6d, 0x3f, 0xb1, 0xc8, 0xee, 0x1d, 0x26, 0x22, 0x11, 0xf6, 0xef, 0xb9,
	0xa9, 0x2a, 0x7d, 0xf0, 0x67, 0x07, 0xb5, 0xce, 0x78, 0x91, 0x2a, 0xc1, 0xf1, 0x11, 0x6a, 0x51,
	0x29, 0x23, 0xe0, 0x05, 0x71, 0xfb, 0xee, 0xd0, 0x9b, 0xee, 0x51, 0x29, 0xcf, 0x78, 0x81, 0x03,
	0xd4, 0x31, 0x42, 0x42, 0x17, 0x10, 0xa5, 0x8c, 0x6c, 0x59, 0xd1, 0xa3, 0x52, 0xbe, 0xa3, 0x0b,
	0x08, 0x19, 0x3e, 0x41, 0x3d, 0xa3, 0xc7, 0x9f, 0x28, 0xe7, 0x90, 0x19, 0xcb, 0xb6, 0xb5, 0x74,
	0xa9, 0x94, 0x6f, 0x2b, 0x18, 0x32, 0x3c, 0x40, 0xbe, 0x71, 0xe5, 0xa0, 0x0a, 0x50, 0xc6, 0xb4,
	0x63, 0x4d, 0xa6, 0xf5, 0xa5, 0x65, 0x21, 0xc3, 0x8f, 0xd1, 0xfe, 0x3f, 0x1e, 0x4e, 0x17, 0x40,
	0x76, 0xad, 0xcb, 0x6f, 0x5c, 0x17, 0x74, 0x01, 0xf5, 0x44, 0x1a, 0xc7, 0x90, 0xe7, 0xd1, 0x1c,
	0x4a, 0xb2, 0xd7, 0x4c, 0x3c, 0xb5, 0xf0, 0x1c, 0xca, 0x7a, 0x62, 0x26, 0x92, 0x28, 0x83, 0x02,
	0x32, 0xd2, 0x6a, 0x26, 0x4e, 0x44, 0x32, 0x31, 0xa8, 0xee, 0x24, 0xa5, 0x12, 0xb3, 0x88, 0x32,
	0xa6, 0xc8, 0xed, 0xa6, 0xd3, 0x7b, 0x03, 0x4f, 0x19, 0x53, 0x75, 0xae, 0x1b, 0xa1, 0xe6, 0x29,
	0x4f, 0x22, 0x96, 0x2a, 0x72, 0xd8, 0xe4, 0xfa, 0x58, 0xd1, 0x71, 0xaa, 0xf0, 0x43, 0xd4, 0x35,
	0xd9, 0xd3, 0x18, 0x22, 0x5d, 0x4a, 0x20, 0xa8, 0x1a, 0xb8, 0x61, 0x57, 0xa5, 0x04, 0x7c, 0x8c,
	0xfc, 0xda, 0x92, 0x72, 0x06, 0x5f, 0x48, 0xa7, 0xef, 0x0e, 0x77, 0xa7, 0xf5, 0xb9, 0xd0, 0x30,
	0xfc, 0x0c, 0xe1, 0xda, 0xc4, 0x40, 0x02, 0x67, 0xc0, 0xe3, 0x92, 0x74, 0x6d, 0xb7, 0x5b, 0x1b,
	0x65, 0xdc, 0x08, 0xf8, 0x3e, 0xf2, 0x40, 0xc7, 0xac, 0xca, 0xef, 0x5b, 0x57, 0xdb, 0x00, 0x9b,
	0xfd, 0x18, 0xf9, 0x56, 0x9c, 0x43, 0x99, 0x4b, 0x1a, 0x03, 0xe9, 0x55, 0x17, 0x34, 0xf0, 0x7c,
	0xc3, 0xcc, 0x33, 0x58, 0x53, 0x06, 0x34, 0x87, 0x48, 0xeb, 0x8c, 0xec, 0x57, 0xb1, 0x0c, 0x9d,
	0x18, 0x78, 0xa5, 0x33, 0xfc, 0x1a, 0xf5, 0x38, 0xe8, 0xc8, 0xae, 0xda, 0x8c, 0xc6, 0x90, 0x93,
	0xbb, 0xfd, 0xed, 0x61, 0xe7, 0xc5, 0xd1, 0xa8, 0x5e, 0xb3, 0x51, 0x58, 0x6b, 0x66, 0xf6, 0xd4,
	0xe7, 0xa0, 0x1b, 0x92, 0x0f, 0x12, 0xe4, 0xff, 0xa7, 0x9b, 0xe0, 0xd7, 0x29, 0xdf, 0x04, 0xaf,
	0x96, 0xae, 0x6d, 0x80, 0x15, 0x1f, 0xa1, 0x1e, 0x65, 0x05, 0x28, 0x9d, 0xe6, 0x50, 0x39, 0xb6,
	0x36, 0x6f, 0x5e, 0x53, 0x6b, 0xc3, 0x68, 0x47, 0x0a, 0xa5, 0xed, 0xce, 0xed, 0x4e, 0x6d, 0x3d,
	0x78, 0x85, 0xda, 0x17, 0x82, 0x41, 0xc8, 0x67, 0xc2, 0xe8, 0x5c, 0x30, 0xb0, 0xed, 0xfd, 0xa9,
	0xad, 0xf1, 0x03, 0xe4, 0x35, 0x97, 0xa8, 0xf7, 0xb9, 0x01, 0x4f, 0x9f, 0x20, 0xcf, 0x9c, 0xbe,
	0xd4, 0x54, 0x03, 0xf6, 0x91, 0x67, 0x8b, 0xb1, 0xb8, 0xe1, 0x07, 0x0e, 0xee, 0xa0, 0x96, 0xfd,
	0xfd, 0x20, 0x0f, 0xdc, 0x37, 0x27, 0xcb, 0xdf, 0x81, 0xf3, 0x63, 0x15, 0xb8, 0xcb, 0x55, 0xe0,
	0xfe, 0x5a, 0x05, 0xee, 0xd7, 0x75, 0xe0, 0x7c, 0x5b, 0x07, 0xce, 0xf7, 0x75, 0xe0, 0x2e, 0xd7,
	0x81, 0xf3, 0x73, 0x1d, 0x38, 0xd7, 0x7b, 0xf6, 0x71, 0x5e, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x73, 0x2b, 0xcd, 0x10, 0xa3, 0x03, 0x00, 0x00,
}

func (m *Environ) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Environ) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Environ) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NetInterfaces) > 0 {
		for iNdEx := len(m.NetInterfaces) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NetInterfaces[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintInternalStruct(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xb2
		}
	}
	if len(m.AppWorkingDir) > 0 {
		i -= len(m.AppWorkingDir)
		copy(dAtA[i:], m.AppWorkingDir)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.AppWorkingDir)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if len(m.AppPprofAddr) > 0 {
		i -= len(m.AppPprofAddr)
		copy(dAtA[i:], m.AppPprofAddr)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.AppPprofAddr)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if m.EtcdLeaseTtl != 0 {
		i = encodeVarintInternalStruct(dAtA, i, uint64(m.EtcdLeaseTtl))
		i--
		dAtA[i] = 0x78
	}
	if len(m.EtcdKeyspace) > 0 {
		i -= len(m.EtcdKeyspace)
		copy(dAtA[i:], m.EtcdKeyspace)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.EtcdKeyspace)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.EtcdAddr) > 0 {
		i -= len(m.EtcdAddr)
		copy(dAtA[i:], m.EtcdAddr)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.EtcdAddr)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.ServiceDependency) > 0 {
		i -= len(m.ServiceDependency)
		copy(dAtA[i:], m.ServiceDependency)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.ServiceDependency)))
		i--
		dAtA[i] = 0x62
	}
	if m.ServiceIndex != 0 {
		i = encodeVarintInternalStruct(dAtA, i, uint64(m.ServiceIndex))
		i--
		dAtA[i] = 0x58
	}
	if len(m.ServiceType) > 0 {
		i -= len(m.ServiceType)
		copy(dAtA[i:], m.ServiceType)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.ServiceType)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.AppLogLevel) > 0 {
		i -= len(m.AppLogLevel)
		copy(dAtA[i:], m.AppLogLevel)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.AppLogLevel)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.AppAccessKey) > 0 {
		i -= len(m.AppAccessKey)
		copy(dAtA[i:], m.AppAccessKey)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.AppAccessKey)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AppServerName) > 0 {
		i -= len(m.AppServerName)
		copy(dAtA[i:], m.AppServerName)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.AppServerName)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AppServerId) > 0 {
		i -= len(m.AppServerId)
		copy(dAtA[i:], m.AppServerId)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.AppServerId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AppChannelId) > 0 {
		i -= len(m.AppChannelId)
		copy(dAtA[i:], m.AppChannelId)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.AppChannelId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AppGameId) > 0 {
		i -= len(m.AppGameId)
		copy(dAtA[i:], m.AppGameId)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.AppGameId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AppEnv) > 0 {
		i -= len(m.AppEnv)
		copy(dAtA[i:], m.AppEnv)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.AppEnv)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InterfaceAddr) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InterfaceAddr) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InterfaceAddr) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Port != 0 {
		i = encodeVarintInternalStruct(dAtA, i, uint64(m.Port))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AdvertiseAddr) > 0 {
		i -= len(m.AdvertiseAddr)
		copy(dAtA[i:], m.AdvertiseAddr)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.AdvertiseAddr)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BindAddr) > 0 {
		i -= len(m.BindAddr)
		copy(dAtA[i:], m.BindAddr)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.BindAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NodeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Interface) > 0 {
		i -= len(m.Interface)
		copy(dAtA[i:], m.Interface)
		i = encodeVarintInternalStruct(dAtA, i, uint64(len(m.Interface)))
		i--
		dAtA[i] = 0x12
	}
	if m.Node != 0 {
		i = encodeVarintInternalStruct(dAtA, i, uint64(m.Node))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintInternalStruct(dAtA []byte, offset int, v uint64) int {
	offset -= sovInternalStruct(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Environ) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AppEnv)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	l = len(m.AppGameId)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	l = len(m.AppChannelId)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	l = len(m.AppServerId)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	l = len(m.AppServerName)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	l = len(m.AppAccessKey)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	l = len(m.AppLogLevel)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	l = len(m.ServiceType)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	if m.ServiceIndex != 0 {
		n += 1 + sovInternalStruct(uint64(m.ServiceIndex))
	}
	l = len(m.ServiceDependency)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	l = len(m.EtcdAddr)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	l = len(m.EtcdKeyspace)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	if m.EtcdLeaseTtl != 0 {
		n += 1 + sovInternalStruct(uint64(m.EtcdLeaseTtl))
	}
	l = len(m.AppPprofAddr)
	if l > 0 {
		n += 2 + l + sovInternalStruct(uint64(l))
	}
	l = len(m.AppWorkingDir)
	if l > 0 {
		n += 2 + l + sovInternalStruct(uint64(l))
	}
	if len(m.NetInterfaces) > 0 {
		for _, e := range m.NetInterfaces {
			l = e.Size()
			n += 2 + l + sovInternalStruct(uint64(l))
		}
	}
	return n
}

func (m *InterfaceAddr) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BindAddr)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	l = len(m.AdvertiseAddr)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	if m.Port != 0 {
		n += 1 + sovInternalStruct(uint64(m.Port))
	}
	return n
}

func (m *NodeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Node != 0 {
		n += 1 + sovInternalStruct(uint64(m.Node))
	}
	l = len(m.Interface)
	if l > 0 {
		n += 1 + l + sovInternalStruct(uint64(l))
	}
	return n
}

func sovInternalStruct(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozInternalStruct(x uint64) (n int) {
	return sovInternalStruct(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Environ) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInternalStruct
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Environ: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Environ: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppEnv", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppEnv = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppGameId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppGameId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppServerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppServerName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppServerName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppAccessKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppAccessKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppLogLevel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppLogLevel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceIndex", wireType)
			}
			m.ServiceIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ServiceIndex |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceDependency", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceDependency = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EtcdAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EtcdAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EtcdKeyspace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EtcdKeyspace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EtcdLeaseTtl", wireType)
			}
			m.EtcdLeaseTtl = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EtcdLeaseTtl |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppPprofAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppPprofAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppWorkingDir", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppWorkingDir = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetInterfaces", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetInterfaces = append(m.NetInterfaces, &InterfaceAddr{})
			if err := m.NetInterfaces[len(m.NetInterfaces)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInternalStruct(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InterfaceAddr) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInternalStruct
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InterfaceAddr: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InterfaceAddr: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BindAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BindAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdvertiseAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AdvertiseAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			m.Port = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Port |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipInternalStruct(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInternalStruct
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			m.Node = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Node |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Interface", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternalStruct
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Interface = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInternalStruct(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInternalStruct
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipInternalStruct(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowInternalStruct
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInternalStruct
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthInternalStruct
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupInternalStruct
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthInternalStruct
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthInternalStruct        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowInternalStruct          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupInternalStruct = fmt.Errorf("proto: unexpected end of group")
)
